- name: "Delete resource records for {{zone}}"
  when: >-
    rr.Op|default("add") == "delete"
  route53:
    state: absent
    zone: "{{ zone }}"
    record: "{{ rr.Name }}"
    type: "{{ rr.Type }}"
    ttl: "{{ rr.TTL|default(ttl)|default(omit) }}"
    value: "{{ rr.ResourceRecords|map(attribute='Value') }}"
    wait: true
  loop: "{{ records }}"
  loop_control:
    loop_var: "rr"
    label: "{{ rr.Name }}/{{ rr.Type }}"

- name: "Create resource records for {{zone}}"
  when: >-
    rr.Op|default("add") == "add"
  route53:
    state: present
    overwrite: "{{ rr.overwrite|default(dns_overwrite)|default(true) }}"
    zone: "{{ zone }}"
    record: "{{ rr.Name }}"
    type: "{{ rr.Type }}"
    ttl: "{{ rr.TTL|default(ttl)|default(omit) }}"
    value: "{{ rr.ResourceRecords|map(attribute='Value') }}"
    wait: true
  loop: "{{ records }}"
  loop_control:
    loop_var: "rr"
    label: "{{ rr.Name }}/{{ rr.Type }}"
